# Evyl Framework Configuration
# Optimized for VPS deployment with large target lists

# Core scanning configuration
scanner:
  threads: 200              # High concurrency for VPS
  timeout: 8                # Optimized timeout
  retry_attempts: 2         # Reduced retries for speed
  user_agent_rotation: true
  proxy_rotation: false     # Disabled for better performance
  request_delay: 0.05       # Minimal delay for speed
  max_redirects: 2          # Reduced redirects
  batch_size: 1000          # Process URLs in batches
  memory_efficient: true    # Enable memory optimization

# Input file processing
input:
  scan_every_line: true     # Ensure every line is scanned
  ignore_duplicates: true   # Skip duplicate targets
  chunk_size: 10000         # Process large files in chunks
  max_file_size: "1GB"      # Maximum target file size

# Validation settings
validation:
  enabled: false            # Disable by default for speed
  parallel_validations: 5   # Reduced for performance
  timeout: 15               # Faster validation timeout

# Output configuration
output:
  formats: ["json"]         # Simplified output
  log_file: "evyl_scan.log" # Always log to file
  real_time_logging: true   # Log results immediately
  compress_results: true
  include_raw_responses: false

# Network optimization
network:
  connection_pooling: true
  pool_size: 300            # Large connection pool
  ssl_verification: false
  follow_redirects: true
  rate_limiting: false      # Disabled for VPS performance

# Module configuration (all enabled by default)
modules:
  kubernetes:
    enabled: true
    deep_scan: true
  aws:
    enabled: true
    metadata_scan: true
  gcp:
    enabled: true
    metadata_scan: true
  azure:
    enabled: true
    metadata_scan: true
  web:
    enabled: true
    comprehensive_scan: true

# Logging configuration
logging:
  level: "INFO"
  file_logging: true
  log_file: "logs/evyl.log"
  colored_output: true
  verbose_errors: true
  performance_stats: true

# Performance optimization for VPS
performance:
  cpu_optimization: true
  memory_limit: "2GB"
  cache_enabled: true
  cache_size: 5000
  async_optimization: true
  
# Security settings
security:
  memory_wiping: false      # Disabled for performance
  credential_obfuscation: true
  secure_logging: true